### ISSUE TITLE
Call for comments: make uvw allocator-aware

### ISSUE THREAD

**Issue by skypjack** [skypjack/uvw#106]
Currently, `uvw` allocates handles and requests using mainly `std::make_shared`. Memory is automatically released when a handle is closed or a request ends.  

Making `uvw` allocator-aware could improve the way it manages memory. Moreover, applications could have a finer control over the memory usage and the allocation policy in general.

I'm not that sure it's worth adding such a feature to the library, but I can have a go with it.  
**If anyone out there is listening, every comment or suggestion is welcome as usual.**

**Comment by skypjack** [comment]
Apparently it isn't a desiderata. It will come with a future release. No pressure to have it anyway.

**Comment by blattersturm** [comment]
At extreme loads (such as when targeted by an application-level attack), our application is spending around 1/3rd of CPU time in the OS heap, with perhaps more wall clock time spent waiting for the OS-level heap lock.

While replacing the allocator globally with a more generic one could mitigate this to some extent (at the expense of potential other unrelated impacts), we typically use a type-specific pool allocator for many other heavily-used but not-too-concurrent structures, including (legacy) raw libuv use.

This library has been extremely valuable to us in reducing the amounts of manual memory management issues regarding libuv handles, but at a clear expense of being stuck using the OS heap for many, many ops.

Having the ability to have (type-specific, not just generic) allocators be specified in some way (ideally, per-loop at the _least_ granular, since we run ~4-12 UV loops per process depending on thread count) would help by a _lot_ since we can use a specialized pool allocator for many such fields without having to relegate to a general-purpose heap allocator.

**Comment by skypjack** [comment]
@blattersturm since you've already investigated the problem and have an easy way to reproduce it, can I ask you what you suggest? I mean, if you had to modify `uvw`, what would you do to address your specific problem?

**Comment by blattersturm** [comment]
> @blattersturm since you've already investigated the problem and have an easy way to reproduce it, can I ask you what you suggest? I mean, if you had to modify `uvw`, what would you do to address your specific problem?

No easy way to _reproduce_ it sadly (most artificial workload generators seem to max out on the wrong end), but we have a large amount of live deployments on end user servers with their owners at times providing profiling traces whenever there's some large network load.

I'm also not sure how this solution would work code-wise (partial templates are a thing I'm somewhat unsure about), but being able to replace the containers used in uvw::Emitter etc. might help, as well as _perhaps_ allowing std::allocator<T>-style allocator specification for allocating other struct types to specialize as needed - I'm not sure what the modern-day equivalent of this is, if any, but a known sizeof(T) is needed for a number of pool libraries we have used before.

As above, given the header-only friendliness, I also don't know how this would would at all without propagating a big `config` type of sorts down the template chain that specifies certain container types and allocator overrides, but it seems to be the solution taken at one point by e.g. the [websocketpp](https://github.com/zaphoyd/websocketpp) library, 

I'm still not 100% sure how much of this allocator load is caused by _our_ code, either, but in an ideal case uvw would approach near-zero overhead compared to directly using libuv's C API, and I feel that the ability to manually manage containers as well as libuv struct allocation _ought_ to help at least reduce some additional point of overhead (for event containers) or allow parity with libuv's C API's flexibility (for struct allocation).

**Comment by skypjack** [comment]
You can already set the allocation functions for libuv, uvw doesn't overwrite them.
On the other side, probably it's enough to allow a per-type allocation policy or a built-in object pool that gets rid of all allocations after the warm up phase. Something that _works_ already out-of-the-box but that users can also specialize on a per-type basis if needed.
So, yeah, I'vea plan (I've already thought about this after all) but it's somewhat costly to do and I've not enough bandwidth in my free time to guarantee an ETA.

**Comment by skypjack** [comment]
@blattersturm any news on this? I mean, have you tracked down the origin of the spikes?
Just curious. Thanks.
