### ISSUE TITLE
Request: CMake library target

### ISSUE THREAD

**Issue by ksergey** [skypjack/uvw#113]
Hello!

Could you please add library target to CMakeLists? I want to use the library as cmake sub-project:
```CMake
add_subdirectory(deps/uvw EXCLUDE_FROM_ALL)
...
add_executable(app ${sources})
target_link_libraries(app skypjack::uvw) # or target_link_libraries(app uvw)
```

In your CMakeLists.txt need to add something like:
```CMake
add_library(uvw INTERFACE)
add_library(skypjack::uvw ALIAS uvw) # optional
target_include_directories(uvw INTERFACE ${LIBUV_DEPS_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/src)
target_link_libraries(uvw INTERFACE ${libuv_static})
target_compile_features(uvw INTERFACE cxx_std_14)
```

Thanks

**Comment by skypjack** [comment]
Could something like [this](https://github.com/skypjack/uvweb/blob/master/cmake/in/uvw.in) work for you?
Otherwise, feel free to create a PR for that, as soon as you tested it and can confirm it works as expected.

**Comment by ksergey** [comment]
@skypjack Yes, this will work for me

**Comment by skypjack** [comment]
@chux0519 Unfortunately I cannot update the link, I deleted the project to which it pointed.  
Btw being header-only, it's quite easy to use `uvw` as a module with cmake. You can find several projects on GitHub that use this library.

**Comment by chux0519** [comment]
> @chux0519 Unfortunately I cannot update the link, I deleted the project to which it pointed.
> Btw being header-only, it's quite easy to use `uvw` as a module with cmake. You can find several projects on GitHub that use this library.

Thank you very much. I think I could figure it out by myself. BTW this project is really cool, Just exactly  what I want.

**Comment by skypjack** [comment]
I'm glad you like it. Are you going to use `uvw` for an open source project? It would be interesting to look at it, if possible.

**Comment by chux0519** [comment]
@skypjack  I'm actually not good at C/C++, just for learning purpose using libuv, and also, I want to use modern C++ instead of unsafe raw C pointers. 

So, I'm planning to write a shadowsocks client(like [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev) but only client side) using uvw, here is the [repo](https://github.com/chux0519/ss-local-uv) (there's still some thing wrong in my CMakeLists.txt). I think I will learn a lot by doing this thing. Thanks again about this project, I'm also curious about the tech which convert C style pointers to smart pointers, the `uvw` is also a good example to read I think.
