### ISSUE TITLE
A small fix in process I/O initialization

### ISSUE THREAD

**Issue by palkarz** [skypjack/uvw#119]
If I understand the intentions correctly, the following code inside `process.hpp`
```
        std::vector<uv_stdio_container_t> poStdio{poFdStdio.size() + poStreamStdio.size()};
        poStdio.insert(poStdio.begin(), poStreamStdio.cbegin(), poStreamStdio.cend());
        poStdio.insert(poStdio.begin(), poFdStdio.cbegin(), poFdStdio.cend());
```
should be changed to something like this:
```
        std::vector<uv_stdio_container_t> poStdio{ poFdStdio.size() + poStreamStdio.size() };
        std::copy(poFdStdio.cbegin(), poFdStdio.cend(), poStdio.begin());
        std::copy(poStreamStdio.cbegin(), poStreamStdio.cend(), poStdio.begin() + poStreamStdio.size());
```
And thanks for the library. It's MUCH nicer to use then the raw libuv.

**Comment by skypjack** [comment]
I'm glad youf ind `uvw` useful. Consider to star it and/or donate if you like the project.  
I don't get your suggestion on the other side. Why should I change those lines? Do you have a test that fail because of how they are written now?

**Comment by palkarz** [comment]
Besides, as far as I understand, the the initial elements in this case can contain arbitrary garbage, so it's actually a potential source of runtime errors.

**Comment by skypjack** [comment]
I'm pretty sure I'm missing something here. This is the current code:
```
std::vector<uv_stdio_container_t> poStdio{poFdStdio.size() + poStreamStdio.size()};
poStdio.insert(poStdio.begin(), poStreamStdio.cbegin(), poStreamStdio.cend());
poStdio.insert(poStdio.begin(), poFdStdio.cbegin(), poFdStdio.cend());
```
It creates a vector of length `poFdStdio.size() + poStreamStdio.size()`, then it inserts `poFdStdio.size() + poStreamStdio.size()` elements and ensures that all what is in `poFdStdio` goes at the top of the array (as requested by `libuv`). `insert` serves exactly that purpose, it copies a range at the specified location and we put everything at the beginning of the resulting vector, both the sources in the right order. Note that the two vectors contain no data or what the user set before.

Why do you say we are putting garbage in the final array here? And why the size looks wrong to you?

I can't spot the error. Probably it's my fault but, please, help me with more details if you know what is wrong because it looks good to me actually.

**Comment by abrownsword** [comment]
Two points:
* constructing a vector with a size_t parameter creates a container that contains that many elements constructed using their default constructor (uv_stdio_container_t likely doesn’t have one, thus ‘garbage’).
* _insert_ allocates space for what it is inserting, and in this case will put that space first in the vector, moving the default-constructed elements further back in the vector (thus you end up with the N you inserted, plus the N you constructed initially).

The proposed solution copies over top of the default constructed elements rather than inserting more elements.  I think my solution would be to instead construct without a parameter, call reserve with the desired size, and then use the original two insert calls (although better would be to insert at end() so that elements are never moved).  Both corrected versions have the same effect in practice (because the element type doesn’t have a constructor), but I don’t like relying on the default construction parameter of vector because it isn’t as explicit as using poStdio.reserve(N).

**Comment by abrownsword** [comment]
https://en.cppreference.com/w/cop/container/vector/vector

Item 3.

**Comment by skypjack** [comment]
Fair enough. Someone is willing to create a PR for that?

**Comment by palkarz** [comment]
Gone with @abrownsword 's suggestion. I think It doesn't matter much in this case, because `uv_stdio_container_t` is just a C-structure. But if it was a class, Andrew's suggestion does seam to avoid extra constructor calls in the case of large collections, if I understand it correctly.

**Comment by abrownsword** [comment]
Thanks, and I echo the sentiment that this is a great library.  Just wish I had the bandwidth to become a maintainer.

**Comment by abrownsword** [comment]
The PR looks good to my eye and includes my 3 suggestions (no constructor arg, use reserve, insert at end).  I haven't tested it (yet).  Assuming someone (palkarz) has actually ensured it compiles and runs, I'd say its good to go.

Unfortunately for me to step up would involve a lot of ramping up on how GitHub and collaborative projects work.  My level of knowledge and experience with this workflow is little more than downloading code and creating an issue or two.  Between my full time work and my home project (and having a life), I don't know when I would be able to ramp up.
