### ISSUE TITLE
Problems building projects

### ISSUE THREAD

**Issue by mulderp** [skypjack/uvw#154]
Hello,

I am on OpenSuse with a separate download of the libuv project.

I tried:
```
cd build 
cmake ..
```

and 

```
cd tests/build
cmake ..
```

Both did not result into some correct build.
Maybe something should be populated in the deps folder. But I see no information what exactly.

Actually i am just trying to build an example in a separate project 

https://github.com/mulderp/uvw_sandbox

Maybe you have some pointers what I can try.

Thanks a lot!

**Comment by skypjack** [comment]
Sorry if I'm late.

The problem is that you're not compiling and therefore linking `libuv`.  
`uvw` is a header-only wrapper but isn't shipped with `libuv`. You've to download, compile and link it yourself and you're not doing it in your project as far as I can see.

That's all. Pretty simple indeed. :-)
