### ISSUE TITLE
cpp14 branch

### ISSUE THREAD

**Issue by maingig** [skypjack/uvw#156]
Please consider having a cpp14 branch.  We have an embedded platform whose compiler does not yet support cpp17.

**Comment by skypjack** [comment]
Hi @maingig 

`uvw` started as a backed project but it's no longer the case and unfortunately I've not enough bandwidth to support two versions nowadays.
To be honest, I'm already struggling to maintain just one version. :smile:

If you're interested in supporting the project or collaborating to maintain a C++14 branch, I'm willing to discuss both the opportunities.

I'm looking forward to your feedback. :+1:

**Comment by maingig** [comment]
Thanks for your response and I understand.  I wish I had the time to help.  I  don't suppose backing out the cpp17 change is an option :-).

**Comment by skypjack** [comment]
Hi @maingig sorry if I'm late, I'm on vacation and I've not much time during these days.

>I don't suppose backing out the cpp17 change is an option :-).

I ported `uvw` to C++17 because it was a step planned since a long time ago and there were several users asking for it. I suspect they would complain of me backing out the C++17 change as well. :-)  
What about collaborating or supporting the project and therefore a C++14 branch instead? Have you considered this option?

If you can say it, may I ask you for what you're using `uvw`? Just curious.

**Comment by skypjack** [comment]
I'm closing this because I suspect you're not interested in a collaboration. Feel free to reopen the issue or contact me directly otherwise. :+1:
