### ISSUE TITLE
Question: Server terminates after one connect

### ISSUE THREAD

**Issue by Merethiel** [skypjack/uvw#158]
I compiled the example code and after one client connects the server just terminates. I tried changing `tcp->once<uvw::ListenEvent>([](const uvw::ListenEvent &, uvw::TCPHandle &srv)` to `tcp->on` and that didn't fix it. Do I have to call loop->run in a while loop? I assumed the loop is done internally as in loop->run should be permanatly blocking unless there is some issue with the listen/accept socket.

**Comment by skypjack** [comment]
`uvw` is a tiny wrapper around `libuv` but it stays true to the behavior of the underlying library. Therefore your guess is right, the loop works as if you were using an `uv_loop_t` and it follows the same rules of its counterpart.

What you're observing is probably due to the fact that both the sockets close their handles after the connection is established (see the invocation of `close()`).  
When the handles are closed, the loop has nothing to elaborate and just returns as it would happen if you were using directly a couple of `uv_tcp_t` and closed them.

Does it make sense to you?

**Comment by Merethiel** [comment]
Ah yes. I didn't even see the call to `ptr->close();` in the client->CloseEvent. Yes that makes a lot of sense. Just commenting out that line keeps the listen socket active and the loop running. Thanks!

**Comment by skypjack** [comment]
That's good. I'm closing the issue. :+1: :wink:

**Comment by skypjack** [comment]
You should use `once` when you want to listen only for the first event of a given type. There are a lot of use cases but all of them are very application specific.

**Comment by Merethiel** [comment]
Thanks!

**Comment by skypjack** [comment]
You're welcome.
