### ISSUE TITLE
Request: Timeout

### ISSUE THREAD

**Issue by Merethiel** [skypjack/uvw#161]
Would it be possible to create a timeout on sockets which invoke an event uvw::TimeOut when a socket has been idle for longer than the requested time.
```
std::chrono::seconds timeoutseconds(30);
auto tcp = loop.resource<uvw::TCPHandle>();
tcp->settimeout(timeoutseconds);
```

Then either the timeout can be reset internally in the library when a read/write is made or the user can invoke a new timeout eachtime a read/write is made by simply calling settimeout again.

**Comment by skypjack** [comment]
What prevents you from doing this with what you've already?
Just create and capture a repeating timer in your callback, then invoke `again` again and again when you receive data.

**Comment by Merethiel** [comment]
I was just curious because it looks like uvw::TCPHandle doesn't have a timer object. I suppose it's its own uvw::TimerHandle? I actually didn't know that was already existant in the code. Sorry.

**Comment by skypjack** [comment]
Nothing to apologize for, don't worry. If I looked rude it's because I answered in a rush from mobile.

Roughly speaking, the tcp handle doesn't have a timer associated because the underlying handle from `libuv` doesn't have it. `uvw` is a tiny wrapper for `libuv` and it stays true to its design and interface. If something doesn't exist in `libuv`, it doesn't exist in `uvw`, because the latter adds nothing but for the memory management and the C++ API.
This helps a lot the users that already know how `libuv' works and it was also the goal initially because I had to migrate an already existing code based on `libuv`.

I hope I answered your question now. :wink:
