### ISSUE TITLE
Question about const correctness of send

### ISSUE THREAD

**Issue by VALERE91** [skypjack/uvw#166]
Hi,

I wanted to ask if there is any mean to send const data over a Handle? 

Thanks

**Comment by skypjack** [comment]
I'm not sure of what handle you're referring to. I'll assume it's the udp handle and therefore its `send` method.
Internally, this function uses the `SendReq` class that invokes [`uv_udp_send`](http://docs.libuv.org/en/v1.x/udp.html#c.uv_udp_send) from the underlying library. The latter receives the data to send by means of an [`uv_buf_t`](http://docs.libuv.org/en/v1.x/misc.html#c.uv_buf_t) that can be initialized with a call to [`uv_buf_init`](http://docs.libuv.org/en/v1.x/misc.html#c.uv_buf_init). As you can see, `uv_buf_init` requires a non-const char pointer and this forces the API of `uvw` to do the same unfortunately.
I suspect the question should be directed to `libuv` rather than `uvw` because the reasons behind the const correctness of this part are buried somewhere in that library. I'm sorry.

**Comment by skypjack** [comment]
I'm closing this. Feel free to reopen if you think you didn't get a proper answer.
