### ISSUE TITLE
Full RAII support?

### ISSUE THREAD

**Issue by adah1972** [skypjack/uvw#172]
Hi Michele,

This seems a good and mature C++ wrapper overall, but I cannot help wondering why the resource management is not fully automatic like the usual RAII case. Are there any specific reasons that prevent you from doing so? I mean, why are all the manual `close()` calls necessary? I'd expect a handle to close automatically when its reference count drops to zero. This is especially intriguing as you are already using `share_ptr`s....

Best regards

**Comment by skypjack** [comment]
Actually, you've both to `init` and `close` handles. Originally, this was to be as true as possible to how `libuv` works, so as to ease the migration of the first codebase in which I used `uvw`. Nowadays it's a matter of not breaking backwards compatibility I guess. I don't remember if there are problems on going full RAII while interacting with `libuv` under the hood but I don't think so.

Note that, because of how `Loop::resource` works, it's quite easy probably to _extend_ the handles and make this automatic.

**Comment by adah1972** [comment]
OK … According to your other answers, you do not have the time to make the change, even if backward compatibility is not an issue (say, make the second call to close do nothing)?

**Comment by skypjack** [comment]
>backward compatibility is not an issue (say, make the second call to close do nothing)

Is this the case? Is `close` idempotent?

**Comment by adah1972** [comment]
No, this is not the case. I meant going that direction…

**Comment by skypjack** [comment]
No, yeah, it's not in `uvw` of course. I meant if this is the case in `libuv`.

**Comment by skypjack** [comment]
I close this issue because it's stuck.
Feel free to reopen it if you need to add something.
Thank you very much.
