### ISSUE TITLE
Update to libuv 1.36

### ISSUE THREAD

**Issue by skypjack** [skypjack/uvw#191]
[Notable changes](https://github.com/libuv/libuv/issues/2787#issuecomment-613447614). Take also a look at the changelog.

**Comment by skypjack** [comment]
@stefanofiorentino I'm pushing all required changes on `experimental`.
I've a warning for a test though, `TEST(FileReq, OpenAndCloseErr)`, line `loop->run();`.
Apparently, we require an instantiation and the definition isn't visible. No idea why it doesn't stop but it may be due to your recent changes.

May I ask you to look into this before merging on `master`? If it's a false positive, don't worry, just let me know so that I can proceed.

Thank you very much!! :heart:

**Comment by stefanofiorentino** [comment]
Please, don't merge until I'll get time to work on it, I'll check it asap.

**Comment by skypjack** [comment]
Yeah, sure, it goes without saying! :smile: 
This is an open source project, no hurry and thank you for helping! :wink:

**Comment by stefanofiorentino** [comment]
The only warning I have regarding test/file_req.cpp is `unused chrono` by cppcheck.
Regrettably, I have to say it's not crystal clear to me the issue you've mentioned, because if an instantiation was missing, either at instantiation time (header-only) or linking time (static/shared libs) we should experience a build error, shouldn't we?
Anyway, I have `all green` tests for both BUILD_UVW_LIBS=ON and OFF.

Tell me more information to be able to repeat the test if needed.

**Comment by skypjack** [comment]
It triggers using `-Wundefined-func-template` with clang 9.
I agree that it we should experience a build error. Maybe a false positive?

**Comment by stefanofiorentino** [comment]
With `that` flag I reproduced the warning, working on this.

**Comment by stefanofiorentino** [comment]
It turns out I missed to "extern instantiate" all templates I moved from hpp to cpp.
As it is well highlighted in this [CppCon2016](https://github.com/CppCon/CppCon2016/blob/master/Tutorials/Template%20Normal%20Programming%2C%20Part%202/Template%20Normal%20Programming%2C%20Part%202%20-%20Arthur%20O'Dwyer%20-%20CppCon%202016.pdf) [pages 43-44], we can either full specialize without implementation or declare the template `extern`, telling the compiler the template has been better defined elsewhere.

**Comment by skypjack** [comment]
A pull from `experimental` solved the problem. Did you push a workaround? Are we ready to go wit the new release?

**Comment by skypjack** [comment]
This kind of things isn't strictly required though:
```
#ifdef UVW_AS_LIB
#include "work.h"
#endif
```
The include guard from `work.h` does it already. This one is somehow redundant. Am I wrong?

**Comment by stefanofiorentino** [comment]
a) I pushed a series of external template instantiations.
b) my clang-tidy warns about unclosed #ifndef, though, it is not stricly required to be pushed on master.

**Comment by skypjack** [comment]
That's good. Ready to go or do you want to push something else?
I think I'll manage to spend some time on this in a couple of days. I'm a bit busy tomorrow unfortunately.

**Comment by stefanofiorentino** [comment]
I think we are ready to merge.

**Comment by skypjack** [comment]
In the meantime, `libuv` v1.37 is out.
I think we could update `uvw` directly to the last version rather than making both steps.

**Comment by skypjack** [comment]
Ok, ready to cut a new release (v2.5.0).
Unless there is a good reason not to do that, I'll proceed tomorrow or during the weekend. :+1:
