### ISSUE TITLE
conversion from void* to the pointer of the base class is not a good idea

### ISSUE THREAD

**Issue by DuckVador** [skypjack/uvw#214]
https://github.com/skypjack/uvw/blob/a10844d4bfd1e31bd062af9aae65add0e70cc136/src/uvw/resource.hpp#L44

https://github.com/skypjack/uvw/blob/a10844d4bfd1e31bd062af9aae65add0e70cc136/src/uvw/loop.cpp#L113

basehandle::type() in uv_walk which is in a timer callback still causes an undefined behavior.

On windows, BaseHandleWalk test failed.
![图片](https://user-images.githubusercontent.com/61409963/88356020-0e30f000-cd99-11ea-8a7d-4f80b4ceb873.png)

Related issue:
https://github.com/skypjack/uvw/issues/212

Reference:
https://stackoverflow.com/a/5445220

**Comment by skypjack** [comment]
@stefanofiorentino ah, the `virtual` breaks things here. I'll look into it after lunch probably.

**Comment by DuckVador** [comment]
@skypjack I have made a pull request which fixes undefined behavior of Loop::walk

**Comment by skypjack** [comment]
I pushed an alternative approach for #215 to branch `experimental`. Please, take a look and give me your feedback. CC @stefanofiorentino 
Long story short: I removed `BaseHandle` and made `Loop::walk` return actual handles. The `Overloaded` class can be used as:
```
loop().walk(uvw::Overloaded{
    [](uvw::AsyncHandle &h){ h.close(); },
    [](uvw::TimerHandle &h){ h.close(); },
    [](auto &&){ /* do nothing for all other handles */ }
});
```
I tried something different because I don't like much the idea of _injecting_ the knowledge of the `Handle<...>` class template into the file for `Resource`. Also, the `downcast` function looks more like something that can fix the problem in the short period but can cause headaches in the long term. Dunno, that was my first impression, I can't really explain it.

I'm looking forward to discussing the two solutions.

**Comment by DuckVador** [comment]
I think the main problem is here. 
https://github.com/skypjack/uvw/blob/a10844d4bfd1e31bd062af9aae65add0e70cc136/src/uvw/resource.hpp#L44
This actually implicitly constrains the order of inheritance. The `resource` class must be inherited first. That's why `Basehandle` crashes. In fact, I support removing the `Basehandle` class, and the downcast approach is only to solve the problem with less modification. A more robust solution is to not assume that the `resource` class is inherited first and execute this line of code in the final class. 
https://github.com/skypjack/uvw/blob/a10844d4bfd1e31bd062af9aae65add0e70cc136/src/uvw/resource.hpp#L44

In addition, `uvw::Overloaded` is a more friendly API than `BaseHandle`.

**Comment by skypjack** [comment]
> A more robust solution is to not assume that the resource class is inherited first and execute this line of code in the final class.

Not sure this would solve the problem though. Because of the multiple inheritance with virtual classes involved, you can't really `static_cast` a `void *` to a `BaseHandle *` if the pointer originally referred a let's say `TCPHandle`. Am I wrong? The two addresses can still differ because the `TCPHandle *` can be the same of either `BaseHandle *` or arbitrarily another `T *` for any of the other base classes. Since this is implementation defined, it's also a subtle bug to spot probably.
That's why I went with an approach that gets rid of the problem at the root. I know it requires more changes but it should also be more _stable_, if you get what I mean.

**Comment by DuckVador** [comment]
I think the problem should be completely resolved now. I have tested other inheritance orders, only when a class with virtual functions will cause the test to fail.
After the experimental branch is merged, this issue can be closed.

**Comment by skypjack** [comment]
Thanks for checking. Let's see if @stefanofiorentino has any feedback on this. Then I'll merge `experimental` on `master` and cut a new minor release. :+1:

**Comment by DuckVador** [comment]
I just opened the Windows tests of the workflow.
![image](https://user-images.githubusercontent.com/61409963/88872610-27c8b080-d24d-11ea-8d57-d5ff938b9c53.png)

Are they platform related tests?
Workflow log ![here](https://github.com/DuckVador/uvw/runs/925835981?check_suite_focus=true).

**Comment by stefanofiorentino** [comment]
@DuckVador cannot undestand which branch/commit you tested again in your last reply.
CI for @skypjack last `experimental` commit looks good to me.
Can you expose further details of your last failure?
ASAN and UBSAN looks also good to me.

**Comment by DuckVador** [comment]
Both the master and experimental branches are test failed in Windows. Note that Linux and macos tests are passed

**Comment by skypjack** [comment]
Yeah, I remember I disabled tests on all platforms because there were things that are supposed to be different on different systems. Btw don't ask the details because it's long time ago! :smile: 
I can re-run all them on Windows during the next days and check them one by one. However, since fwiw all boil down to the underlying library, it's likely to be the case above mentioned.

Any help to investigate is appreciated ofc. :)

**Comment by stefanofiorentino** [comment]
> The log is here: https://github.com/DuckVador/uvw/runs/925835981?check_suite_focus=true.
Now it's crystal clear, you added the "Run tests" in windows and macos too. 
Never tried that before. 
We _definitely_ should run the -DBUILD_UVW_LIBS=OFF version to ensure that **also** the static linking is broken in Windows.

**Comment by skypjack** [comment]
Ok, let's investigate this before merging on master. I suggest to work with experimental, that is the candidate for the merge at the moment. :+1:

**Comment by skypjack** [comment]
So, first of all, the test for the loop fails because it invokes `fork` and it's not implemented on Windows. By default, this one returns an error and this triggers an assert in the test.
We can get around it with a platform-based `if` probably.

**Comment by skypjack** [comment]
Same thing for `util.cpp`. We check that `shell` isn't empty but it's returned as null by `libuv` only on Windows. No bugs here fortunately, we can get around this with the same `if`.

**Comment by skypjack** [comment]
Same for `tty.cpp`. The console for testing isn't readable on Windows (for some reasons) and therefore changing its mode fails because libuv returns an error. We can easily get around it by checking that the handle is also readable before setting the mode.

**Comment by skypjack** [comment]
Same for the threading stuff. Apparently, if you try to lock an already locked mutex, you receive falso on Linux and true on Windows. The difference boils down to the underlying library and doesn't depend by `uvw`. We can get around it with a platform dependent `if` to make it work.

**Comment by skypjack** [comment]
Same for `pipe.cpp`, it's a naming issue. On Windows, the pipe name has a fixed format and differs from that used in the test that is good only for Unix like systems instead.
Quite easy to fix, still no bugs in `uvw`.

**Comment by skypjack** [comment]
@DuckVador can I ask you to confirm that all tests passes from experimental except one, that is the send file fs utility?
As for the latter, apparently it's a regression in libuv on Windows, see [this issue](https://github.com/libuv/libuv/issues/2076) for further details. I won't update the test because clearly the bug isn't in uvw.

**Comment by DuckVador** [comment]
@skypjack 

I recompiled these tests on `experimental` branch. The following detail is all on Windows.

-  `fs_poll` test is not successful every time. It hangs most of the time. But if I exchange https://github.com/skypjack/uvw/blob/91ab230d81f42bc3bf0c38e5599abb6527bedb5f/test/uvw/fs_poll.cpp#L29 and https://github.com/skypjack/uvw/blob/91ab230d81f42bc3bf0c38e5599abb6527bedb5f/test/uvw/fs_poll.cpp#L30, it passes every time.
- `tty` test is successful if I run `exe` directly. Buf if call `CTest`, `tty` test fails every time.
![image](https://user-images.githubusercontent.com/61409963/89094312-26d28300-d3f5-11ea-9632-7ca8acc27c3e.png)
![image](https://user-images.githubusercontent.com/61409963/89094336-6ac58800-d3f5-11ea-8f6b-7573f1d313d9.png)
![image](https://user-images.githubusercontent.com/61409963/89094344-7a44d100-d3f5-11ea-9f1a-d861ac7c5a51.png)

**Comment by skypjack** [comment]
These two boil down to the differences between systems. Again. I wouldn't care much.

**Comment by DuckVador** [comment]
Good, I have no more questions about Windows. Looking forward to merging the experimental branch.
