### ISSUE TITLE
ProcessHandle::stdio problems and improvement

### ISSUE THREAD

**Issue by raoulh** [skypjack/uvw#82]
Multiple point here:
1- When trying to use
```
template<typename T>
ProcessHandle& stdio(Flags<StdIO> flags, FileHandle fd);
```
What is the use of T ? I think it should be removed, right?

2- Another problem I have is doing that:
```
proc->stdio(uvw::ProcessHandle::StdIO::CREATE_PIPE | uvw::ProcessHandle::StdIO::READABLE_PIPE, pipe);
```
It fails to build because of the | (OR) operator that is not found. Am I missing something here?

3- Finally, the stdio() API could be somehow improved because it is painful to do something like:
```
  uv_pipe_init(uv_default_loop(), &out, 0);
  options.stdio = stdio;
  options.stdio[0].flags = UV_IGNORE;
  options.stdio[1].flags = UV_CREATE_PIPE | UV_WRITABLE_PIPE;
  options.stdio[1].data.stream = (uv_stream_t*)&out;
  options.stdio_count = 2;
  r = uv_spawn(uv_default_loop(), &process, &options);
```
is not working right now using uvw (or I missed something?) I tried to do this:
```
  pipe = uvw::Loop::getDefault()->resource<uvw::PipeHandle>();
  proc->stdio(uvw::ProcessHandle::StdIO::IGNORE_STREAM, static_cast<uvw::FileHandle>(0));
  //The ignore stream flag I must use FileHandle(0)... ?

  proc->stdio(uvw::ProcessHandle::StdIO::CREATE_PIPE | uvw::ProcessHandle::StdIO::READABLE_PIPE, *pipe);
```

**Comment by skypjack** [comment]
1.
Right, removed. Thank you. I'm trying to do my best to add more and more tests, but your help is really appreciated!!

2.
Values are actually `enum class`es. The expression tries to _or_ them before to construct a `Flags` object and fails because values from an `enum class` cannot be composed that way.
The best you can do is something like this:

    handle->stdio(uvw::Flags<uvw::ProcessHandle::StdIO>{uvw::ProcessHandle::StdIO::CREATE_PIPE} | uvw::ProcessHandle::StdIO::READABLE_PIPE, *pipe);

Or this:

    auto flags = uvw::Flags<uvw::ProcessHandle::StdIO>{};
    handle->stdio(flags | uvw::ProcessHandle::StdIO::CREATE_PIPE | uvw::ProcessHandle::StdIO::READABLE_PIPE, *pipe);

3.
The example seems to be affected by the same problem discussed above. Moreover you forgot the flag uvw::ProcessHandle::StdIO::IGNORE.
Flags are somehow tricky to use, it will be far easier with C++17 because of the auto deduction of template parameters from constructor parameters.

Let me know if the issue still persists and how I can help you or if you solved the problems.

**Comment by skypjack** [comment]
I plan to switch flags from enum classes to old fashioned ones. This way users can easily use the `|` operator.
Can I close the issue for the other points no longer apply?

**Comment by raoulh** [comment]
1- Sure, Rome wasn't built in one day ;)
2- I would prefer to have old fashioned enum types, as we could directly pass the libuv ones instead of having to handle weird wrappers.
3- What bother me with the example is that in C, you can just call `stdio[0].flags = UV_IGNORE`, but in uvw you need to pass also a 0 FileHandle with a cast. This is not really clear I think, although it works.

**Comment by skypjack** [comment]
1. Ok, done. Upstream since a couple of days. Thank you.

2. The policy of `uvw` is to hide completely libuv. Future changes won't impact users hopefully. Therefore, enum types will be wrapped in any case. The fact is that old fashioned enums are more flexible when used in combination with the `Flags` class. Anyway, I'm considering closed the issue, for you have a _valid_ alternative right now and soon we'll probably have the above mentioned switch.

3. I guess it's due to my ignorance about use cases for pipes. If you have any suggestion, let me know and we can find a solution to give a nicer interface to the users.

**Comment by raoulh** [comment]
Thanks for all your answer, I can close this issue now.

**Comment by skypjack** [comment]
Note about `Flags`.
Switching to unscoped enums leads to a bunch of problems mainly due to the fact that names become part of the surrounding scope.
Therefore I decided to go straight with scoped enums.

Anyway, I'm to push a new member function `Flags<E>::from` that you can use as it follows:

    enum class E { FOO = 1, BAR = 2, END = 8 };
    // ...
    auto flags = Flags<E>::from<E::FOO, E::BAR>();

This likely will solve the problems you are encountering with scoped enums.

**Comment by skypjack** [comment]
I'm to push a slightly changed `ProcessHandle` to try to help you on point 3.
I've updated the documentation as well. Let me know if it works for you now.
It will be upstream probably at the end of the week.
