### ISSUE TITLE
multithread and shared_ptr usage

### ISSUE THREAD

**Issue by flipcoder** [skypjack/uvw#96]
So I've heard libuv doesn't have a good way to support multi-thread out of the box (possibly something as easy as spawning a separate loop in each thread, not sure).   It would be nice if uvw had a way to wrap the event loop this way optionally.  If this is a welcome feature I may contribute once I get it working.

Also, using shared_ptr in single-threaded cases might not be worth the overhead in a library like this. 
boost::shared_ptr<> has similar problems and using the single-thread define would enforce its use in the rest of the code.   So, I'm thinking migrate to a system where the smart ptr impl can be selected by the user somehow, or pick a good alternative.

I'll probably contribute to development of this soon, since I'm quite interested in seeing something similar to node.js happen with C++ (was also interested in node.native).

**Comment by skypjack** [comment]
A few thoughts:

* As far as I know `node.native` is no longer under development. With [a comment to an issue](https://github.com/d5/node.native/issues/39#issuecomment-301136469) I invited to contribute to `uvw` all the ones that were interested in a _node-like_ library in C++. Unfortunately, there had been no contributions so far.

* `std::shared_ptr` and `std::enable_shared_from_this` are the corner stone of `uvw`. The internal `leak`/`reset` functionalities are entirely designed upon them. I'm not sure we can replace them with different tools but for something that is really close to what the standard library offers. `boost::shared_ptr` could be probably a good alternative. Anyway keep in mind that not all the projects can pay the burden of pulling in boost and I don't want to make boost a mandatory dependency of `uvw`. So, the first choice *must* remain the `std:.shared_ptr` (or a switch to a completely different approach that works without `std::shared_ptr`, if you know of it).
Have you already thought about how to let users choose their preferred implementation?

* I don't know what you mean with - _libuv doesn't have a good way to support multi-thread_. It's an event loop based library, so it is meant to run on a single thread. It offers a thread pool in case you need to use threads and keep them consistent within the loop. Otherwise `<thread>` is at your disposal.
If your goal is to create more than one loop and run them on different threads instead, well, that's how usually things are made with such a library. `uvw` supports it out-of-the-box as `libuv` does. I don't see what is missed exactly.
Please, give me more details and I'll be glad to give you a feedback.

That being said, PR are welcome. I cannot promise each and every PR will be accepted, but I'll look into all of them and try to get the best out of them.
If you want to contribute to `uvw` but you find that you want also to discuss changes before to make them, feel free to ping me and we can discuss proposals here or in a chat.

**Comment by flipcoder** [comment]
The reason I bring up shared_ptr is that if someone is using uvw on a single-core webhost or wishing to spawn 1 process per core instead, the overhead of the atomic refcount is unnecessary.

I guess the easiest solution is making a #define for using a drop-in replacement for shared_ptr, defaulting to std::shared_ptr.  (Also it's possible that certain parts of the code don't require the atomic at all, since they can be assumed to be accessed from one thread always anyway.  I'll look into this when I get the chance.)

And you're right about libuv.  There seem to already be solutions for what I'm wanting.

Also, what are your plans for uvweb?  Is this the start of something node-like?

**Comment by skypjack** [comment]
I thought about it.

Approximately `uvw` takes the lock on the shared pointer twice during the lifecycle of an handle (something similar applies to the requests): when you initialize it (because of a call to `shared_from_this`) and when you close it (for it resets the internal pointer).  
Each and every time an event is sent, you get a reference obtained by dereferencing the pointer, thus no lock. When you create an handle, copy elision hopefully solves the issue and we can move it otherwise, thus no lock.  
At the end of the day, all the other locks are there because of an user of the library that decides either to copy the pointer obtained when the handle is created or to invoke `shared_from_this` on a reference in a callback.  
If users code carefully, I don't think the performance hit introduced by `uvw` (if any) can even be noticeable.

Back to the possible approach, if you find that it's worth it.  
I wouldn't fill all the headers with macros. It would become quickly a maintenance hell.  
Instead, I'd probably put the macros aside and use them to decide which (let me say) _memory traits_ use, then I'd use the traits transparently all around the code. This way, if someone comes up with a third choice in future, we don't have to modify all the headers once more. Instead it will be a matter of a new `elif` within the cascade of macros that sets up the right traits to use.  
Did you get the idea?

Again, I don't think the penalty is worth introducing another tool to replace `std::shared_ptr`, anyway feel free to make your proposal or have another go to convince me. ;-)

---

`uvweb`. Well, the idea is to create a non-header-only library based upon `uvw` to offer SSL support, HTTP stuff and so on.  
Unfortunately I haven't had the time to work on it yet. Sooner or later... Probably... Would you be interested in participating to the project?

**Comment by flipcoder** [comment]
Yeah, you make good point about the in-frequencies of the atomic ops. Thanks for considering it though.

As for uvweb, let's do it!

**Comment by skypjack** [comment]
It would be great. If you want to come onboard, you'd be welcome.
